# Your project's server will run on xxxx:xxxx 
ENVIRONMENT:
  LOCAL:
    HOST: localhost
    PORT: 8000

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    # Search for used CSS classes in generated HTML files
    - "./**/*.php"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "./static"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/**/*"
    - "!src/{img,js,sass}"
    - "!src/{img,js,sass}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/js/app.js"